version: '3.4'

services:
  statping:
    image: hunterlong/statping
    restart: always
    ports:
      - 127.0.0.1:8081:8080
    volumes:
      - ./data:/app
    environment:
      DB_CONN: sqlite
      ADMIN_USER: admin
      ADMIN_PASSWORD: admin